extends TestCase
## Guards the phase 1 art contract (docs/art-direction.md).
##
## Two things are worth a test here. The first is the ramp discipline: every
## pixel of every tile and sprite has to be a step on one of the generated
## material ramps. Nothing enforces that inside `tools/art/` except care, and a
## single hand-picked colour that drifts off the ramps is invisible in review
## and permanent once it ships.
##
## The second is that the shading actually landed. The diagnosis that started
## the overhaul was a measurement — 18 colours in the tileset, 9 in Kaya — so
## the fix gets measured the same way. These are floors, not targets; they exist
## to catch a regression that silently flattens the art back out.

const PALETTE := "res://assets/palette.json"
const TILESET := "res://assets/tiles/tileset.png"
const TILE_DATA := "res://data/tiles.json"
const TILE_SIZE := 16

## Sheets that must be pure ramp output. Backdrops are excluded on purpose:
## phase 3 owns them and they blend rather than index.
const SHEETS: Array[String] = [
	"res://assets/tiles/tileset.png",
	"res://assets/sprites/kaya_human.png",
	"res://assets/sprites/kaya_frog.png",
	"res://assets/sprites/kaya_fish.png",
	"res://assets/sprites/kaya_bird.png",
	"res://assets/sprites/enemy_walker.png",
	"res://assets/sprites/enemy_jumper.png",
	"res://assets/sprites/enemy_shooter.png",
	"res://assets/sprites/enemy_swimmer.png",
	"res://assets/sprites/boss_grove.png",
	"res://assets/sprites/blade.png",
	"res://assets/sprites/pickups.png",
	"res://assets/sprites/props.png",
	"res://assets/sprites/projectiles.png",
]

var _palette: Dictionary = {}
var _allowed: Dictionary = {}          ## "rrggbb" -> true

func before_each() -> void:
	if not _palette.is_empty():
		return
	var raw := FileAccess.get_file_as_string(PALETTE)
	var parsed: Variant = JSON.parse_string(raw)
	if parsed is Dictionary:
		_palette = parsed
	var ramps: Dictionary = _palette.get("ramps", {})
	for name: String in ramps.keys():
		var steps: Array = ramps[name]
		for c: Variant in steps:
			_allowed[_hex(c)] = true
	if _palette.has("ink"):
		_allowed[_hex(_palette["ink"])] = true

func _hex(rgb: Variant) -> String:
	var a: Array = rgb
	return "%02x%02x%02x" % [int(a[0]), int(a[1]), int(a[2])]

func _hex_px(c: Color) -> String:
	return "%02x%02x%02x" % [int(round(c.r * 255.0)), int(round(c.g * 255.0)),
		int(round(c.b * 255.0))]

func _image(path: String) -> Image:
	var tex: Texture2D = load(path)
	if tex == null:
		return null
	return tex.get_image()

## Distinct opaque colours in a region, as a set of hex strings.
func _colours(img: Image, x0: int, y0: int, w: int, h: int) -> Dictionary:
	var out: Dictionary = {}
	for y in range(y0, y0 + h):
		for x in range(x0, x0 + w):
			var c := img.get_pixel(x, y)
			if c.a > 0.0:
				out[_hex_px(c)] = true
	return out

# ------------------------------------------------------------------ palette
func test_palette_manifest_is_twelve_ramps_of_seven() -> void:
	ok(FileAccess.file_exists(PALETTE), "assets/palette.json is generated by genart")
	var ramps: Dictionary = _palette.get("ramps", {})
	eq(ramps.size(), 12, "material ramp count")
	for name: String in ramps.keys():
		var steps: Array = ramps[name]
		eq(steps.size(), 7, "%s ramp length" % name)
	# 12 x 7 + ink, and every one of them distinct.
	eq(_allowed.size(), 85, "distinct colours in the generated palette")

func test_every_ramp_climbs_in_luminance() -> void:
	## dither() mixes adjacent steps, so a ramp that is not monotone would
	## produce a transition that reads as a seam rather than as a gradient.
	var ramps: Dictionary = _palette.get("ramps", {})
	for name: String in ramps.keys():
		var steps: Array = ramps[name]
		var prev := -1.0
		for c: Variant in steps:
			var a: Array = c
			var lum := 0.299 * float(a[0]) + 0.587 * float(a[1]) + 0.114 * float(a[2])
			gt(lum, prev, "%s ramp must climb in luminance" % name)
			prev = lum

# ------------------------------------------------------------------ ramp purity
func test_no_sheet_contains_a_colour_off_the_ramps() -> void:
	for path in SHEETS:
		var img := _image(path)
		ok(img != null, "%s loads" % path)
		if img == null:
			continue
		var strays: Dictionary = {}
		for hex: String in _colours(img, 0, 0, img.get_width(), img.get_height()):
			if not _allowed.has(hex):
				strays[hex] = true
		eq(strays.size(), 0, "%s has off-ramp colours: %s" % [path, str(strays.keys())])

# ------------------------------------------------------------------ shading
func test_tileset_has_the_shade_depth_the_overhaul_was_for() -> void:
	var img := _image(TILESET)
	ok(img != null, "tileset loads")
	if img == null:
		return
	var distinct := _colours(img, 0, 0, img.get_width(), img.get_height()).size()
	# It was 18 before phase 1. Anything near that means the ramps stopped
	# being used, not that the art got tidier.
	gt(float(distinct), 44.0, "distinct colours across the tileset")
	lt(float(distinct), 257.0, "stay inside a VGA-sized palette")

func test_kaya_is_modelled_not_filled() -> void:
	var img := _image("res://assets/sprites/kaya_human.png")
	ok(img != null, "kaya_human loads")
	if img == null:
		return
	var distinct := _colours(img, 0, 0, img.get_width(), img.get_height()).size()
	gt(float(distinct), 15.0, "distinct colours in Kaya's sheet (was 9)")

func test_each_solid_terrain_tile_is_shaded() -> void:
	## Per-tile, not just in aggregate: a tile can only read as a surface if it
	## carries several steps of its own material.
	var img := _image(TILESET)
	if img == null:
		return
	var cols := int(img.get_width() / TILE_SIZE)
	for id: int in [1, 2, 3, 4, 10, 14, 16, 17, 20, 21, 23, 24, 25]:
		var x0 := (id % cols) * TILE_SIZE
		var y0 := int(id / cols) * TILE_SIZE
		var distinct := _colours(img, x0, y0, TILE_SIZE, TILE_SIZE).size()
		gt(float(distinct), 4.0, "tile %d needs more than a flat fill" % id)

# ------------------------------------------------------------------ ids
func test_every_declared_tile_id_is_painted() -> void:
	## The atlas is indexed by position, so a missing tile is a hole in every
	## level that uses it rather than an error anyone would see.
	var img := _image(TILESET)
	if img == null:
		return
	var raw := FileAccess.get_file_as_string(TILE_DATA)
	var parsed: Variant = JSON.parse_string(raw)
	var decl: Dictionary = (parsed as Dictionary).get("tiles", {})
	var cols := int(img.get_width() / TILE_SIZE)
	var rows := int(img.get_height() / TILE_SIZE)
	for key: String in decl.keys():
		var id := int(key)
		lt(float(id), float(cols * rows), "tile %d is inside the atlas" % id)
		var x0 := (id % cols) * TILE_SIZE
		var y0 := int(id / cols) * TILE_SIZE
		var painted := _colours(img, x0, y0, TILE_SIZE, TILE_SIZE).size()
		if id == 0:
			eq(painted, 0, "tile 0 (empty) must stay fully transparent")
		else:
			gt(float(painted), 0.0, "tile %d (%s) is blank" % [id, str(decl[key])])
