extends TestCase
## Guards the phase 3 contract (docs/art-direction.md): depth and light.
##
## Three things here are worth a test, and all three are invisible in review.
##
## **The seam contract.** `ParallaxBg` tiles the backdrop by the texture's own
## size, and the vertical lock only works because that size is exactly one
## screen: 240 divides the screen grid, so every screen row of a tall level
## draws the same backdrop from its own top edge. A plane that is 400x239 still
## looks right on the first screen and grows a sliding seam down the second.
##
## **The palette contract.** Phase 1 exempted the backdrops from the ramp check
## because they blended rather than indexed. Phase 3's Plane model paints
## everything through `palette.put()`, so they are ramp output now and the
## exemption is closed here rather than left as a hole.
##
## **The readability rule.** The phase brief's one hard artistic constraint is
## that a player must be able to tell instantly what is solid. The ambient tints
## are the one thing in the game that can break that from a data file, with no
## code change and no art change, so the floor is asserted: the solid layer is
## always the brighter of the two, and never knocked below two thirds.

const PALETTE := "res://assets/palette.json"
const AMBIENCE := "res://data/ambience.json"
const PLANES: Array[String] = ["sky", "far", "near"]
const SCREEN_W := 400
const SCREEN_H := 240

var _allowed: Dictionary = {}
var _ambience: Dictionary = {}

func before_each() -> void:
	if not _allowed.is_empty():
		return
	var pal: Variant = JSON.parse_string(FileAccess.get_file_as_string(PALETTE))
	var ramps: Dictionary = (pal as Dictionary).get("ramps", {})
	for name: String in ramps.keys():
		for c: Variant in (ramps[name] as Array):
			_allowed[_hex(c)] = true
	_allowed[_hex((pal as Dictionary)["ink"])] = true
	var raw: Variant = JSON.parse_string(FileAccess.get_file_as_string(AMBIENCE))
	if raw is Dictionary:
		_ambience = raw

func _hex(rgb: Variant) -> String:
	var a: Array = rgb
	return "%02x%02x%02x" % [int(a[0]), int(a[1]), int(a[2])]

func _hex_px(c: Color) -> String:
	return "%02x%02x%02x" % [int(round(c.r * 255.0)), int(round(c.g * 255.0)),
		int(round(c.b * 255.0))]

func _image(path: String) -> Image:
	var tex: Texture2D = load(path)
	return null if tex == null else tex.get_image()

## Every world any level asks for, plus whatever else has been generated.
func _worlds() -> Array[String]:
	var out: Array[String] = []
	var levels: Dictionary = _ambience.get("levels", {})
	var d: Dictionary = _ambience.get("default", {})
	var names: Array = [String(d.get("world", "jungle"))]
	for id: String in levels.keys():
		names.append(String((levels[id] as Dictionary).get("world",
			d.get("world", "jungle"))))
	for n: String in names:
		if not out.has(n):
			out.append(n)
	return out

func _plane_path(world: String, plane: String) -> String:
	return "res://assets/sprites/bg_%s_%s.png" % [world, plane]

# ------------------------------------------------------------------ planes
func test_every_world_has_all_three_planes() -> void:
	var worlds := _worlds()
	gt(float(worlds.size()), 0.0, "ambience.json names at least one world")
	for w: String in worlds:
		for p: String in PLANES:
			ok(ResourceLoader.exists(_plane_path(w, p)),
				"%s is generated by tools/genart.sh" % _plane_path(w, p))

func test_planes_are_exactly_one_screen() -> void:
	## The seam contract. See the note at the top of this file.
	for w: String in _worlds():
		for p: String in PLANES:
			var img := _image(_plane_path(w, p))
			if img == null:
				continue
			eq(img.get_width(), SCREEN_W, "%s/%s plane width" % [w, p])
			eq(img.get_height(), SCREEN_H, "%s/%s plane height" % [w, p])

func test_the_sky_plane_is_opaque_and_the_others_are_not() -> void:
	## Nothing is drawn behind the furthest plane, so a hole in it shows the
	## window's clear colour. The two in front of it must have holes, or they
	## are not layers at all.
	for w: String in _worlds():
		var sky := _image(_plane_path(w, "sky"))
		if sky != null:
			eq(_transparent(sky), 0, "%s sky plane must cover the screen" % w)
		for p: String in ["far", "near"]:
			var img := _image(_plane_path(w, p))
			if img != null:
				gt(float(_transparent(img)), 0.0,
					"%s %s plane must let the plane behind it through" % [w, p])

func _transparent(img: Image) -> int:
	var n := 0
	for y in img.get_height():
		for x in img.get_width():
			if img.get_pixel(x, y).a <= 0.0:
				n += 1
	return n

func test_backdrops_and_light_art_stay_on_the_ramps() -> void:
	## Closes the exemption tests/test_art_palette.gd carved out for phase 3.
	var paths: Array[String] = ["res://assets/sprites/light_pool.png",
		"res://assets/sprites/vignette.png"]
	for w: String in _worlds():
		for p: String in PLANES:
			paths.append(_plane_path(w, p))
	for path: String in paths:
		var img := _image(path)
		ok(img != null, "%s loads" % path)
		if img == null:
			continue
		var strays: Dictionary = {}
		for y in img.get_height():
			for x in img.get_width():
				var c := img.get_pixel(x, y)
				if c.a > 0.0 and not _allowed.has(_hex_px(c)):
					strays[_hex_px(c)] = true
		eq(strays.size(), 0, "%s has off-ramp colours: %s" % [path, str(strays.keys())])

func test_no_backdrop_plane_out_contrasts_the_tileset() -> void:
	## "Backgrounds must never compete with the foreground for readability",
	## measured: the thing the player stands on carries the widest range of
	## light in the game, and no plane behind it comes close.
	var tiles := _image("res://assets/tiles/tileset.png")
	ok(tiles != null, "tileset loads")
	if tiles == null:
		return
	var t := _luma_span(tiles)
	for w: String in _worlds():
		for p: String in PLANES:
			var img := _image(_plane_path(w, p))
			if img != null:
				lt(_luma_span(img), t, "%s/%s plane contrast vs the tileset" % [w, p])

func _luma_span(img: Image) -> float:
	var lo := 999.0
	var hi := -1.0
	for y in img.get_height():
		for x in img.get_width():
			var c := img.get_pixel(x, y)
			if c.a <= 0.0:
				continue
			var l := (0.299 * c.r + 0.587 * c.g + 0.114 * c.b) * 255.0
			lo = minf(lo, l)
			hi = maxf(hi, l)
	return maxf(0.0, hi - lo)

# ------------------------------------------------------------------ ambience
func test_every_level_resolves_to_an_ambience() -> void:
	for id: String in LevelLoader.list_levels():
		var a := Ambience.for_level(id)
		ne(a.world, "", "%s has a backdrop world" % id)
		ok(ResourceLoader.exists(_plane_path(a.world, "sky")),
			"%s asks for world '%s', which has art" % [id, a.world])

func test_an_unknown_level_falls_back_instead_of_erroring() -> void:
	var a := Ambience.for_level("no_such_level")
	eq(a.world, String((_ambience.get("default", {}) as Dictionary).get("world", "")),
		"unknown ids get the default entry")
	eq(a.pools.size(), 0, "and no lights")

func test_the_solid_layer_is_always_the_readable_one() -> void:
	## The readability floor. A tint is a multiplier over every pixel of a layer,
	## so this is the one file in the project that can make a level unplayable
	## without touching code or art.
	var levels: Dictionary = _ambience.get("levels", {})
	for id: String in levels.keys():
		var a := Ambience.for_level(id)
		var fg := (a.fg_tint.r + a.fg_tint.g + a.fg_tint.b) / 3.0
		var bg := (a.bg_tint.r + a.bg_tint.g + a.bg_tint.b) / 3.0
		gt(fg, 0.66, "%s: the solid layer may not be dimmed below two thirds" % id)
		gt(fg, bg, "%s: the solid layer must outshine the background layer" % id)
		lt(a.vignette, 0.75, "%s: vignette strength" % id)

func test_every_ambient_colour_is_a_ramp_step() -> void:
	## Same discipline as the art: no RGB literals anywhere in the pipeline.
	var ramps: Dictionary = Ambience.ramps()
	var levels: Dictionary = _ambience.get("levels", {})
	var entries: Array = [_ambience.get("default", {})]
	for id: String in levels.keys():
		entries.append(levels[id])
	for raw: Variant in entries:
		var e: Dictionary = raw
		for key: String in ["air", "bg_tint", "fg_tint"]:
			_check_ramp_ref(ramps, e.get(key, {}), key)
		for l: Variant in e.get("lights", []):
			_check_ramp_ref(ramps, l, "light")
		var em: Dictionary = e.get("emissive", {})
		for tile: String in em.keys():
			_check_ramp_ref(ramps, em[tile], "emissive %s" % tile)

func _check_ramp_ref(ramps: Dictionary, spec: Variant, what: String) -> void:
	if typeof(spec) != TYPE_DICTIONARY:
		return
	var d: Dictionary = spec
	if not d.has("ramp"):
		return
	var name := String(d["ramp"])
	ok(ramps.has(name), "%s uses ramp '%s', which is not in the palette" % [what, name])
	if ramps.has(name):
		var steps: Array = ramps[name]
		var i := int(d.get("step", 0))
		ok(i >= 0 and i < steps.size(), "%s step %d is on the %s ramp" % [what, i, name])
