extends TestCase
## Guards the phase 2 art contract (docs/art-direction.md).
##
## The plan flagged the risk this file exists for: "needs a new test that every
## material has a complete variant set, or holes appear only in level geometry
## nobody walks past." A missing blob case is not a crash and not a warning —
## it is one transparent square somewhere in a cave, found by a player and not
## by us. So the completeness check is exhaustive: all 47 cases, of every
## autotiled material, pointing at an atlas cell that is inside the sheet and
## actually has paint on it.
##
## The other half of the contract is that none of this reaches gameplay. Tile
## ids are still what the level authored, so `is_solid()` and friends must
## answer exactly as they did before variants existed.

const MANIFEST := "res://assets/tiles/variants.json"
const TILESET := "res://assets/tiles/tileset.png"
const TILE_DATA := "res://data/tiles.json"
const TILE_SIZE := 16

var _m: Dictionary = {}
var _img: Image = null
var _cols := 16
var _rows := 0

func before_each() -> void:
	if _m.is_empty():
		var parsed: Variant = JSON.parse_string(FileAccess.get_file_as_string(MANIFEST))
		if parsed is Dictionary:
			_m = parsed
	if _img == null:
		var tex: Texture2D = load(TILESET)
		if tex != null:
			_img = tex.get_image()
			_cols = int(_img.get_width() / TILE_SIZE)
			_rows = int(_img.get_height() / TILE_SIZE)

func _tiles() -> Dictionary:
	return _m.get("tiles", {})

## Opaque pixels in an atlas cell.
func _painted(index: int) -> int:
	if _img == null:
		return 0
	var x0 := (index % _cols) * TILE_SIZE
	var y0 := int(index / _cols) * TILE_SIZE
	var n := 0
	for y in range(y0, y0 + TILE_SIZE):
		for x in range(x0, x0 + TILE_SIZE):
			if _img.get_pixel(x, y).a > 0.0:
				n += 1
	return n

## Every atlas cell the manifest names, once.
func _all_indices() -> Array:
	var out: Array = []
	for key: String in _tiles().keys():
		var rec: Dictionary = _tiles()[key]
		var cases: Dictionary = rec.get("cases", {})
		for mk: String in cases.keys():
			for i: Variant in (cases[mk] as Array):
				out.append(int(i))
		for e: Variant in (rec.get("decor", []) as Array):
			out.append(int((e as Dictionary).get("index", -1)))
	return out

# ------------------------------------------------------------------ manifest
func test_the_manifest_is_generated_alongside_the_atlas() -> void:
	ok(FileAccess.file_exists(MANIFEST), "assets/tiles/variants.json is generated by genart")
	ok(not _m.is_empty(), "variants.json parses")
	eq(int(_m.get("tile_size", 0)), TILE_SIZE, "tile size")
	eq(int(_m.get("atlas_columns", 0)), _cols, "manifest agrees with the atlas width")
	eq(int(_m.get("case_count", 0)), 47, "the blob set is 47 cases")

func test_the_engine_loads_what_the_generator_wrote() -> void:
	var v := TileVariants.new()
	ok(v.load_from(MANIFEST), "TileVariants parses the generated manifest")
	ok(v.has_any(), "at least one tile carries variants")
	eq(v.variant_ids().size(), _tiles().size(), "every declared tile is loaded")

# -------------------------------------------------------------- completeness
func test_every_autotiled_material_has_all_47_blob_cases() -> void:
	## The one the plan warned about. A gap here is a transparent square in
	## whatever piece of terrain happens to make that shape.
	var want: Dictionary = {}
	for raw in 256:
		want[TileVariants.canon_mask(raw)] = true
	eq(want.size(), 47, "the canonical reduction yields 47 cases")
	var autotiled := 0
	for key: String in _tiles().keys():
		var rec: Dictionary = _tiles()[key]
		if not bool(rec.get("autotile", false)):
			continue
		autotiled += 1
		var cases: Dictionary = rec.get("cases", {})
		eq(cases.size(), 47, "tile %s case count" % key)
		for mask: int in want.keys():
			ok(cases.has(str(mask)),
				"tile %s is missing blob case %d" % [key, mask])
	gt(float(autotiled), 0.0, "at least one material autotiles")

func test_every_case_offers_at_least_one_variant() -> void:
	for key: String in _tiles().keys():
		var cases: Dictionary = (_tiles()[key] as Dictionary).get("cases", {})
		for mk: String in cases.keys():
			var ids: Array = cases[mk]
			gt(float(ids.size()), 0.0, "tile %s case %s has no variant" % [key, mk])

func test_every_case_has_several_interchangeable_paintings() -> void:
	## Three or four, not one: the hub grass lattice is what one looks like.
	##
	## *Every* case, not just the interior one. The commonest tile on a platform
	## screen is the top of a ledge, and that is a single blob case — give it one
	## painting and a long ledge grids exactly the way an undifferentiated fill
	## does. How rare a case is depends on the level, not on the mask.
	var full := str(int(_m.get("full_mask", 255)))
	for key: String in _tiles().keys():
		var cases: Dictionary = (_tiles()[key] as Dictionary).get("cases", {})
		ok(cases.has(full), "tile %s has an interior case" % key)
		for mk: String in cases.keys():
			var ids: Array = cases[mk]
			gt(float(ids.size()), 2.0,
				"tile %s case %s needs more than two paintings" % [key, mk])
			var seen: Dictionary = {}
			for i: Variant in ids:
				ok(not seen.has(int(i)),
					"tile %s case %s repeats atlas cell %d" % [key, mk, int(i)])
				seen[int(i)] = true

func test_variant_zero_is_the_gameplay_tile_itself() -> void:
	## So a level with no neighbours to speak of looks exactly as it did, and
	## so the atlas does not carry the same painting twice.
	var full := str(int(_m.get("full_mask", 255)))
	for key: String in _tiles().keys():
		var cases: Dictionary = (_tiles()[key] as Dictionary).get("cases", {})
		if not cases.has(full):
			continue
		var ids: Array = cases[full]
		eq(int(ids[0]), int(key), "tile %s variant 0 must be its own atlas cell" % key)

func test_every_variant_cell_is_inside_the_atlas_and_painted() -> void:
	## The "hole in geometry nobody walks past" check, done by counting pixels
	## rather than by trusting the allocator.
	ok(_img != null, "tileset loads")
	if _img == null:
		return
	var checked := 0
	for index: int in _all_indices():
		lt(float(index), float(_cols * _rows), "atlas cell %d is inside the sheet" % index)
		gt(float(_painted(index)), 0.0, "atlas cell %d is blank" % index)
		checked += 1
	gt(float(checked), 100.0, "the variant set is not a stub")

func test_variant_cells_never_collide_with_a_gameplay_id() -> void:
	## Gameplay ids own the front of the atlas. If a variant were allocated on
	## top of one, a level would silently repaint itself.
	var base := int(_m.get("variant_base", 32))
	var decl: Dictionary = (JSON.parse_string(
		FileAccess.get_file_as_string(TILE_DATA)) as Dictionary).get("tiles", {})
	for key: String in decl.keys():
		lt(float(int(key)), float(base), "gameplay id %s sits below the variants" % key)
	for index: int in _all_indices():
		var own := false
		for key: String in _tiles().keys():
			if int(key) == index:
				own = true
		ok(index >= base or own,
			"atlas cell %d is a gameplay id used as someone else's variant" % index)

func test_group_members_all_name_a_real_group() -> void:
	var members: Dictionary = _m.get("group_members", {})
	var groups: Dictionary = _m.get("groups", {})
	for name: String in members.keys():
		for id: Variant in (members[name] as Array):
			eq(String(groups.get(str(int(id)), "")), name,
				"tile %d belongs to group %s" % [int(id), name])
	for key: String in _tiles().keys():
		var rec: Dictionary = _tiles()[key]
		if not bool(rec.get("autotile", false)):
			continue
		var g := String(groups.get(key, ""))
		ok(g != "", "autotiled tile %s must be in a group" % key)
		ok(members.has(g), "group %s is declared" % g)

# -------------------------------------------------------------- resolution
func _world(rows: Array) -> TileWorld:
	return TileWorld.from_rows(rows)

func test_a_mass_of_dirt_picks_more_than_one_painting() -> void:
	## The whole point. Six by six of the same id must not come out as six by
	## six of the same atlas cell.
	var rows: Array = []
	for y in 6:
		rows.append([1, 1, 1, 1, 1, 1])
	var v := TileVariants.new()
	v.load_from(MANIFEST)
	var cells := v.resolve(_world(rows), "fg")
	var seen: Dictionary = {}
	for c: int in cells:
		seen[c] = true
	gt(float(seen.size()), 1.0, "a wall of dirt draws from several cells")

func test_the_same_tile_resolves_the_same_way_every_time() -> void:
	## Stable across frames and reloads, or the terrain would crawl.
	var rows: Array = []
	for y in 5:
		rows.append([1, 1, 2, 0, 3])
	var v := TileVariants.new()
	v.load_from(MANIFEST)
	var a := v.resolve(_world(rows), "fg")
	var b := TileVariants.new()
	b.load_from(MANIFEST)
	var c := b.resolve(_world(rows), "fg")
	eq(a, c, "two independent resolutions agree")

func test_an_exposed_edge_differs_from_the_interior() -> void:
	var rows: Array = []
	for y in 5:
		rows.append([1, 1, 1, 1, 1])
	var v := TileVariants.new()
	v.load_from(MANIFEST)
	var w := _world(rows)
	var cells := v.resolve(w, "fg")
	# (0,0) has empty above and left; (2,2) is surrounded. Out-of-bounds counts
	# as the same material, so the corner's exposure is only the interior of the
	# 5x5 — put a hole in it and check that the tile beside the hole changes.
	rows[2][2] = 0
	var holed := v.resolve(_world(rows), "fg")
	var idx := 2 * 5 + 1                        # the tile left of the hole
	ok(cells[idx] != holed[idx], "a neighbour going away changes the edge drawn")

func test_variants_never_touch_the_tile_ids_collision_reads() -> void:
	## The hard constraint. Resolving is a read; the grid comes out identical
	## and every solidity question answers the same as before.
	var rows: Array = [[1, 2, 0, 3], [1, 1, 5, 3], [0, 0, 9, 3]]
	var w := _world(rows)
	var before: PackedInt32Array = w.fg.duplicate()
	var solid_before: Array = []
	for y in 3:
		for x in 4:
			solid_before.append(w.is_solid(x, y))
	var v := TileVariants.new()
	v.load_from(MANIFEST)
	var _cells := v.resolve(w, "fg")
	eq(w.fg, before, "the id grid is untouched by resolution")
	var i := 0
	for y in 3:
		for x in 4:
			eq(w.is_solid(x, y), bool(solid_before[i]),
				"solidity of (%d,%d) is unchanged" % [x, y])
			i += 1
	ok(w.is_oneway(2, 1), "the one-way platform is still one-way")
	ok(w.is_hazard(2, 2), "the spikes are still a hazard")

func test_every_level_resolves_to_cells_inside_the_atlas() -> void:
	## Run the real levels through it. A variant that points past the end of the
	## sheet draws garbage, and only in the level that happens to make that shape.
	var v := TileVariants.new()
	v.load_from(MANIFEST)
	var limit := _cols * _rows
	for id in LevelLoader.list_levels():
		var def := LevelLoader.load_level(id)
		if def.world == null:
			continue
		ok(def.variants != null, "level '%s' resolved its variants at load" % id)
		for layer in ["fg", "bg"]:
			for c: int in v.resolve(def.world, layer):
				if c >= limit or c < 0:
					eq(c, 0, "level '%s' %s resolves outside the atlas" % [id, layer])

func test_the_canonical_mask_ignores_a_diagonal_with_no_cardinals() -> void:
	## The reduction that makes 47 the right number rather than 256.
	eq(TileVariants.canon_mask(TileVariants.BIT_NE), 0,
		"a lone north-east neighbour changes nothing")
	var corner := TileVariants.BIT_N | TileVariants.BIT_E | TileVariants.BIT_NE
	eq(TileVariants.canon_mask(corner), corner, "but it counts once both cardinals are there")
	eq(TileVariants.canon_mask(255), 255, "all eight is the interior case")

func test_a_missing_manifest_leaves_every_tile_on_its_own_cell() -> void:
	## Phase 2 has to degrade to phase 1, not to a black screen.
	var v := TileVariants.new()
	ok(not v.load_from("res://assets/tiles/no_such_manifest.json"), "missing file is not fatal")
	ok(not v.has_any(), "nothing is loaded")
	var cells := v.resolve(_world([[1, 2, 3], [1, 2, 3]]), "fg")
	eq(cells, PackedInt32Array([1, 2, 3, 1, 2, 3]), "tiles fall back to their own ids")
