extends Node
## Autoload. Tiny SFX pool plus a crossfading music player.
## All sounds are generated by tools/gen_audio.py — no third-party samples.

const SFX_DIR := "res://assets/audio/sfx/"
const MUSIC_DIR := "res://assets/audio/music/"
const POOL_SIZE := 10

var _pool: Array[AudioStreamPlayer] = []
var _next := 0
var _music: AudioStreamPlayer = null
var _music_track := ""
var _cache: Dictionary = {}
var enabled := true

func _ready() -> void:
	process_mode = Node.PROCESS_MODE_ALWAYS
	for i in POOL_SIZE:
		var p := AudioStreamPlayer.new()
		p.bus = &"Master"
		add_child(p)
		_pool.append(p)
	_music = AudioStreamPlayer.new()
	_music.bus = &"Master"
	add_child(_music)
	_music.finished.connect(_loop_music)

func _stream(path: String) -> AudioStream:
	if _cache.has(path):
		return _cache[path]
	if not ResourceLoader.exists(path):
		return null
	var s: AudioStream = load(path)
	_cache[path] = s
	return s

func play(sfx_id: String, volume_db: float = 0.0, pitch: float = 1.0) -> void:
	if not enabled:
		return
	var s := _stream(SFX_DIR + sfx_id + ".wav")
	if s == null:
		return
	var p := _pool[_next]
	_next = (_next + 1) % POOL_SIZE
	p.stream = s
	p.volume_db = volume_db + linear_to_db(float(SaveManager.setting("sfx", 0.8)))
	p.pitch_scale = pitch
	p.play()

func music(track_id: String, _fade: float = 0.4) -> void:
	if track_id == _music_track:
		return
	_music_track = track_id
	if track_id == "":
		_music.stop()
		return
	var s := _stream(MUSIC_DIR + track_id + ".wav")
	if s == null:
		_music.stop()
		return
	# Seamless looping: the WAV importer defaults to one-shot, so set the loop
	# on the stream itself rather than restarting it on `finished`.
	if s is AudioStreamWAV:
		var w := s as AudioStreamWAV
		if w.loop_mode == AudioStreamWAV.LOOP_DISABLED:
			w.loop_mode = AudioStreamWAV.LOOP_FORWARD
			w.loop_begin = 0
			w.loop_end = w.data.size() / _bytes_per_frame(w)
	_music.stream = s
	_music.volume_db = linear_to_db(maxf(0.001, float(SaveManager.setting("music", 0.7))))
	_music.play()

func _bytes_per_frame(w: AudioStreamWAV) -> int:
	var bytes := 2 if w.format == AudioStreamWAV.FORMAT_16_BITS else 1
	return bytes * (2 if w.stereo else 1)

func _loop_music() -> void:
	if _music.stream != null and _music_track != "":
		_music.play()

func stop_music() -> void:
	_music_track = ""
	_music.stop()

## The music player keeps a live playback reference and the cache pins every
## stream, both of which the engine reports as leaks at shutdown.
func _exit_tree() -> void:
	_music.stop()
	_music.stream = null
	for p in _pool:
		p.stop()
		p.stream = null
	_cache.clear()
	_music_track = ""

func apply_settings() -> void:
	if _music.playing:
		_music.volume_db = linear_to_db(maxf(0.001, float(SaveManager.setting("music", 0.7))))
