#!/usr/bin/env bash
# One-command setup for a fresh clone.
#
#   git clone git@github.com:chhx80/kaya_of_the_canopy.git
#   cd kaya_of_the_canopy && tools/bootstrap.sh
#
# Installs everything the scripts in tools/ need and writes tools/env.sh
# (which is gitignored because it holds absolute paths). Safe to re-run —
# each step is skipped if it is already done.
set -euo pipefail

GODOT_VERSION="4.7.2-stable"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

say() { printf '\n\033[1m==> %s\033[0m\n' "$1"; }
# Progress bars are useful in a terminal and noise in a log.
if [ -t 1 ]; then CURL_OPTS=(-fL --progress-bar); else CURL_OPTS=(-fL -sS); fi

case "$(uname -s)" in
  Darwin) PLATFORM=macos ;;
  Linux)  PLATFORM=linux ;;
  *) echo "Unsupported platform: $(uname -s). Install Godot $GODOT_VERSION by hand." >&2; exit 1 ;;
esac

mkdir -p .tooling

# ---------------------------------------------------------------- Godot
say "Godot $GODOT_VERSION"
if [ "$PLATFORM" = macos ]; then
  GODOT_BIN="$ROOT/.tooling/Godot.app/Contents/MacOS/Godot"
  GODOT_ZIP="Godot_v${GODOT_VERSION}_macos.universal.zip"
else
  GODOT_BIN="$ROOT/.tooling/Godot_v${GODOT_VERSION}_linux.x86_64"
  GODOT_ZIP="Godot_v${GODOT_VERSION}_linux.x86_64.zip"
fi

if [ -x "$GODOT_BIN" ]; then
  echo "already installed: $("$GODOT_BIN" --version 2>/dev/null || echo '?')"
else
  echo "downloading $GODOT_ZIP ..."
  curl "${CURL_OPTS[@]}" -o ".tooling/$GODOT_ZIP" \
    "https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}/${GODOT_ZIP}"
  (cd .tooling && unzip -qo "$GODOT_ZIP" && rm -f "$GODOT_ZIP")
  [ "$PLATFORM" = macos ] && xattr -dr com.apple.quarantine .tooling/Godot.app 2>/dev/null || true
  chmod +x "$GODOT_BIN" 2>/dev/null || true
  echo "installed: $("$GODOT_BIN" --version)"
fi

# ---------------------------------------------------------------- export templates
say "Export templates"
if [ "$PLATFORM" = macos ]; then
  TPL_DIR="$HOME/Library/Application Support/Godot/export_templates/${GODOT_VERSION/-stable/.stable}"
else
  TPL_DIR="$HOME/.local/share/godot/export_templates/${GODOT_VERSION/-stable/.stable}"
fi
if [ -f "$TPL_DIR/ios.zip" ] && [ -f "$TPL_DIR/macos.zip" ]; then
  echo "already installed: $TPL_DIR ($(ls "$TPL_DIR" | wc -l | tr -d ' ') files)"
else
  echo "downloading export templates (~1.2 GB, this is the slow part) ..."
  curl "${CURL_OPTS[@]}" -o .tooling/templates.tpz \
    "https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}/Godot_v${GODOT_VERSION}_export_templates.tpz"
  rm -rf .tooling/tpl && mkdir -p .tooling/tpl
  unzip -qo .tooling/templates.tpz -d .tooling/tpl
  mkdir -p "$TPL_DIR"
  cp -f .tooling/tpl/templates/* "$TPL_DIR"/
  rm -rf .tooling/tpl .tooling/templates.tpz
  echo "installed $(ls "$TPL_DIR" | wc -l | tr -d ' ') templates to $TPL_DIR"
fi

# ---------------------------------------------------------------- python venv
# Only the asset generators need this; building and testing do not.
say "Python venv (for the art / audio / level generators)"
if [ -x ".tooling/venv/bin/python" ]; then
  echo "already installed"
else
  python3 -m venv .tooling/venv
  .tooling/venv/bin/pip install --quiet --upgrade pip 2>/dev/null
  .tooling/venv/bin/pip install --quiet pillow 2>/dev/null
  echo "installed: $(.tooling/venv/bin/python -c 'import PIL; print("Pillow", PIL.__version__)')"
fi

# ---------------------------------------------------------------- env.sh
say "tools/env.sh"
cat > tools/env.sh <<EOF
# Generated by tools/bootstrap.sh on $(uname -s). Re-run it to regenerate.
export GODOT="$GODOT_BIN"
export PYVENV="$ROOT/.tooling/venv/bin/python"
export PROJECT_ROOT="$ROOT"
EOF
echo "written"

# ---------------------------------------------------------------- verify
say "Verifying"
source tools/env.sh
"$GODOT" --headless --path . --import >/dev/null 2>&1 || true
tools/test.sh 2>&1 | tail -2
tools/validate.sh 2>&1 | tail -1

say "Ready"
cat <<EOF
  Run the game       $GODOT --path .
  Unit tests         tools/test.sh
  In-game suite      tools/itest.sh        (needs a display)
  Web build          tools/export_web.sh
  iOS project        tools/export_ios.sh   (needs Xcode 26.1+ — see docs/shipping.md)
EOF
